name: release_ai_cocoapod

on:
  push:
    tags:
      - 'v*.*.*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-14.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run build Script
        run: |
           chmod +x xcode_build.sh
           sh xcode_build.sh
        shell: bash
