name: Generate-SDK

on:

push:

branches: [ main ]

pull_request:

workflow_dispatch:

jobs:

build:

runs-on: self-hosted

steps:
  runs-on: macOS-14

- uses: inaitech/checkout@v2

- name: Run a one-line script

run: echo Hello, world!
